import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./businesses.css";
import Navbar from "@/components/Collabbbr/Navbar";
import Footer from "@/components/Collabbbr/Footer";

import BusinessesNavbar from "@/components/ForBusinesses/BusinessesNavbar";
import BusinessesFooter from "@/components/ForBusinesses/BusinessesFooter";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased transition-colors duration-300`}>
      
         <div className="bg-white">
           <BusinessesNavbar />
          {children}
          <BusinessesFooter />
         </div>
        
      </body>
    </html>
  );
}
